# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b97d0611cb3caa538bff4ef64d069bfb502e7b0cb54699abb96a413e6223c146178edaa3110a4f5012d2f11b34c2c2ebacb9275c40f44e348130e5ff2f24759

test:
  secret_key_base: fdca6a42568318e136717b9d4689c4fb8c020a78d152b94288caccb0695faf62b2994c30c3fc9946f117a73f1b550066e7de3fb6743579e8e9298f1defa75e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
